const allQuestions = [
// ===== TONES (1-10) =====
{id:1,cat:"tones",q:"The tone pattern 55 represents:",opts:["2nd tone","3rd tone","1st tone","Neutral"],ans:2},
{id:2,cat:"tones",q:"The tone pattern 35 represents:",opts:["1st tone","2nd tone","3rd tone","4th tone"],ans:1},
{id:3,cat:"tones",q:"The tone pattern 214 represents:",opts:["1st tone","3rd tone","4th tone","Neutral"],ans:1},
{id:4,cat:"tones",q:"The tone pattern 51 represents:",opts:["2nd tone","3rd tone","4th tone","Neutral"],ans:2},
{id:5,cat:"tones",q:"The neutral tone is represented by:",opts:["0","1","2","5"],ans:0},
{id:6,cat:"tones",q:"The first tone is pronounced as:",opts:["Rising","Falling","High and flat","Low"],ans:2},
{id:7,cat:"tones",q:"The second tone is:",opts:["Rising","Falling","Flat","Neutral"],ans:0},
{id:8,cat:"tones",q:"The third tone sound pattern is:",opts:["Rise","Dip then rise","Fall","Flat"],ans:1},
{id:9,cat:"tones",q:"The fourth tone sound pattern is:",opts:["Rising","Falling sharply","Flat","Neutral"],ans:1},
{id:10,cat:"tones",q:"Mandarin has how many main tones?",opts:["3","4","5","6"],ans:1},
// ===== PRONOUNS (11-50) =====
{id:11,cat:"pronouns",q:"Wǒ means:",opts:["You","I / Me","He","They"],ans:1},
{id:12,cat:"pronouns",q:"Wǒmen means:",opts:["We","You","They","He"],ans:0},
{id:13,cat:"pronouns",q:"Nǐ means:",opts:["I","You","They","He"],ans:1},
{id:14,cat:"pronouns",q:"Nín is used for:",opts:["Children","Informal speech","Respectful \"you\"","Plural"],ans:2},
{id:15,cat:"pronouns",q:"Tā means:",opts:["We","He/She/It","You","They"],ans:1},
{id:16,cat:"pronouns",q:"Tāmen means:",opts:["They","We","You","He"],ans:0},
{id:17,cat:"pronouns",q:"Nǐmen means:",opts:["You (plural)","They","We","He"],ans:0},
{id:18,cat:"pronouns",q:"Nínmen means:",opts:["Respectful plural \"you\"","They","I","We"],ans:0},
{id:19,cat:"pronouns",q:"Wǒ de means:",opts:["Your","My","His","Their"],ans:1},
{id:20,cat:"pronouns",q:"Nǐ de means:",opts:["Your","My","Their","Our"],ans:0},
{id:21,cat:"pronouns",q:"Tā de means:",opts:["My","Your","His/Her","Our"],ans:2},
{id:22,cat:"pronouns",q:"Wǒmen de means:",opts:["Our","Your","Their","His"],ans:0},
{id:23,cat:"pronouns",q:"Nǐmen de means:",opts:["Their","Your (plural)","Our","His"],ans:1},
{id:24,cat:"pronouns",q:"Tāmen de means:",opts:["Our","Their","My","Your"],ans:1},
{id:25,cat:"pronouns",q:"Wǒ shì means:",opts:["I am","You are","He is","They are"],ans:0},
{id:26,cat:"pronouns",q:"Nǐ shì means:",opts:["You are","I am","He is","They are"],ans:0},
{id:27,cat:"pronouns",q:"Tā shì means:",opts:["He/She is","You are","I am","They are"],ans:0},
{id:28,cat:"pronouns",q:"Wǒmen shì means:",opts:["We are","You are","They are","I am"],ans:0},
{id:29,cat:"pronouns",q:"Nǐmen shì means:",opts:["They are","You are (plural)","We are","I am"],ans:1},
{id:30,cat:"pronouns",q:"Tāmen shì means:",opts:["They are","We are","You are","He is"],ans:0},
{id:31,cat:"pronouns",q:"Mandarin Chinese mainly uses:",opts:["3 tones","4 tones","5 tones","6 tones"],ans:1},
{id:32,cat:"pronouns",q:"Which word means I?",opts:["Nǐ","Tā","Wǒ","Nín"],ans:2},
{id:33,cat:"pronouns",q:"Which word means we?",opts:["Wǒmen","Nǐmen","Tāmen","Nínmen"],ans:0},
{id:34,cat:"pronouns",q:"Which word means you (informal)?",opts:["Nǐ","Tā","Wǒ","Nín"],ans:0},
{id:35,cat:"pronouns",q:"Which word means respectful you?",opts:["Wǒ","Nǐ","Nín","Tā"],ans:2},
{id:36,cat:"pronouns",q:"Which word means they?",opts:["Wǒmen","Tāmen","Nǐmen","Nínmen"],ans:1},
{id:37,cat:"pronouns",q:"Tā can mean:",opts:["I","He / She / It","You","We"],ans:1},
{id:38,cat:"pronouns",q:"Nǐmen means:",opts:["You (plural)","We","They","He"],ans:0},
{id:39,cat:"pronouns",q:"Nínmen is used for:",opts:["Informal plural","Respectful plural \"you\"","They","We"],ans:1},
{id:40,cat:"pronouns",q:"Which pronoun is singular?",opts:["Wǒmen","Tāmen","Wǒ","Nǐmen"],ans:2},
{id:41,cat:"pronouns",q:"Which pronoun refers to a group of people?",opts:["Wǒ","Nǐ","Tā","Tāmen"],ans:3},
{id:42,cat:"pronouns",q:"The word de in Mandarin shows:",opts:["Action","Possession","Time","Question"],ans:1},
{id:43,cat:"pronouns",q:"Wǒ de means:",opts:["Your","My","Their","Our"],ans:1},
{id:44,cat:"pronouns",q:"Nǐ de means:",opts:["Your","My","His","Our"],ans:0},
{id:45,cat:"pronouns",q:"Tā de means:",opts:["His/Her","Your","My","Our"],ans:0},
{id:46,cat:"pronouns",q:"Wǒmen de means:",opts:["Our","Their","Your","His"],ans:0},
{id:47,cat:"pronouns",q:"Nǐmen de means:",opts:["Your (plural)","My","Their","Our"],ans:0},
{id:48,cat:"pronouns",q:"Tāmen de means:",opts:["Our","My","Their","Your"],ans:2},
{id:49,cat:"pronouns",q:"The correct translation of \"my teacher\" is:",opts:["Wǒ de laoshi","Nǐ de laoshi","Tā de laoshi","Wǒmen laoshi"],ans:0},
{id:50,cat:"pronouns",q:"Your book in Mandarin would start with:",opts:["Wǒ de","Nǐ de","Tā de","Wǒmen de"],ans:1},
// ===== SENTENCES (51-98) =====
{id:51,cat:"sentences",q:"Their house would begin with:",opts:["Wǒ de","Nǐ de","Tāmen de","Wǒmen de"],ans:2},
{id:52,cat:"sentences",q:"The word Shì means:",opts:["To go","To be","To eat","To see"],ans:1},
{id:53,cat:"sentences",q:"Wǒ shì translates to:",opts:["I am","You are","He is","They are"],ans:0},
{id:54,cat:"sentences",q:"Nǐ shì means:",opts:["You are","I am","He is","They are"],ans:0},
{id:55,cat:"sentences",q:"Tā shì means:",opts:["He/She is","I am","You are","They are"],ans:0},
{id:56,cat:"sentences",q:"Wǒmen shì means:",opts:["We are","They are","You are","He is"],ans:0},
{id:57,cat:"sentences",q:"Nǐmen shì means:",opts:["You are (plural)","We are","They are","I am"],ans:0},
{id:58,cat:"sentences",q:"Tāmen shì means:",opts:["They are","We are","You are","He is"],ans:0},
{id:59,cat:"sentences",q:"Which sentence means \"We are students\"?",opts:["Wǒmen shì xuesheng","Nǐ shì xuesheng","Tā shì xuesheng","Wǒ shì xuesheng"],ans:0},
{id:60,cat:"sentences",q:"Which sentence means \"He is a teacher\"?",opts:["Tā shì laoshi","Nǐ shì laoshi","Wǒ shì laoshi","Wǒmen shì laoshi"],ans:0},
{id:61,cat:"sentences",q:"Which sentence means \"You are a student\"?",opts:["Nǐ shì xuesheng","Tā shì xuesheng","Wǒ shì xuesheng","Tāmen shì xuesheng"],ans:0},
{id:62,cat:"sentences",q:"The particle de connects:",opts:["Verb and subject","Owner and object","Question and answer","Tone and sound"],ans:1},
{id:63,cat:"sentences",q:"Which phrase means my friend?",opts:["Nǐ de pengyou","Wǒ de pengyou","Tā de pengyou","Wǒmen pengyou"],ans:1},
{id:64,cat:"sentences",q:"Which phrase means your teacher?",opts:["Wǒ de laoshi","Nǐ de laoshi","Tā de laoshi","Wǒmen laoshi"],ans:1},
{id:65,cat:"sentences",q:"Which phrase means his book?",opts:["Tā de shu","Nǐ de shu","Wǒ de shu","Wǒmen shu"],ans:0},
{id:66,cat:"sentences",q:"Which phrase means our class?",opts:["Wǒmen de ban","Tāmen de ban","Nǐmen ban","Wǒ ban"],ans:0},
{id:67,cat:"sentences",q:"Which phrase means their house?",opts:["Wǒmen de jia","Tāmen de jia","Nǐ de jia","Tā de jia"],ans:1},
{id:68,cat:"sentences",q:"Nǐ de péngyou means:",opts:["My friend","Your friend","Their friend","Our friend"],ans:1},
{id:69,cat:"sentences",q:"Tā de jiā means:",opts:["My house","His/Her house","Your house","Their house"],ans:1},
{id:70,cat:"sentences",q:"Wǒmen de lǎoshī means:",opts:["Their teacher","Our teacher","My teacher","Your teacher"],ans:1},
{id:71,cat:"sentences",q:"Nǐmen de xuéshēng means:",opts:["Your students","Their students","Our students","My students"],ans:0},
{id:72,cat:"sentences",q:"Tāmen de xuéxiào means:",opts:["Our school","Their school","My school","Your school"],ans:1},
{id:73,cat:"sentences",q:"The word shì functions as:",opts:["Noun","Verb","Adjective","Pronoun"],ans:1},
{id:74,cat:"sentences",q:"Wǒ shì lǎoshī means:",opts:["I am a teacher","You are a teacher","He is a teacher","They are teachers"],ans:0},
{id:75,cat:"sentences",q:"Nǐ shì xuéshēng means:",opts:["You are a student","I am a student","He is a student","They are students"],ans:0},
{id:76,cat:"sentences",q:"Tā shì lǎoshī means:",opts:["She/He is a teacher","You are a teacher","I am a teacher","They are teachers"],ans:0},
{id:77,cat:"sentences",q:"Wǒmen shì xuéshēng means:",opts:["We are students","They are students","You are students","He is a student"],ans:0},
{id:78,cat:"sentences",q:"Nǐmen shì xuéshēng means:",opts:["You are students","We are students","They are students","I am a student"],ans:0},
{id:79,cat:"sentences",q:"Tāmen shì lǎoshī means:",opts:["They are teachers","We are teachers","You are teachers","He is a teacher"],ans:0},
{id:80,cat:"sentences",q:"Which word means teacher?",opts:["Lǎoshī","Xuéshēng","Péngyou","Jiā"],ans:0},
{id:81,cat:"sentences",q:"Which word means student?",opts:["Lǎoshī","Xuéshēng","Jiā","Péngyou"],ans:1},
{id:82,cat:"sentences",q:"Which word means friend?",opts:["Lǎoshī","Xuéshēng","Péngyou","Jiā"],ans:2},
{id:83,cat:"sentences",q:"Which word means house/home?",opts:["Jiā","Péngyou","Lǎoshī","Xuéshēng"],ans:0},
{id:84,cat:"sentences",q:"Which phrase means your friend?",opts:["Wǒ de péngyou","Nǐ de péngyou","Tā de péngyou","Wǒmen péngyou"],ans:1},
{id:85,cat:"sentences",q:"Which phrase means their school?",opts:["Wǒ de xuéxiào","Nǐ de xuéxiào","Tāmen de xuéxiào","Wǒmen xuéxiào"],ans:2},
{id:86,cat:"sentences",q:"Which phrase means our teacher?",opts:["Wǒmen de lǎoshī","Nǐmen de lǎoshī","Tāmen de lǎoshī","Wǒ de lǎoshī"],ans:0},
{id:87,cat:"sentences",q:"Which phrase means his friend?",opts:["Tā de péngyou","Nǐ de péngyou","Wǒ de péngyou","Wǒmen péngyou"],ans:0},
{id:88,cat:"sentences",q:"Which phrase means your students?",opts:["Nǐmen de xuéshēng","Wǒmen de xuéshēng","Tāmen de xuéshēng","Wǒ de xuéshēng"],ans:0},
{id:89,cat:"sentences",q:"Which sentence means \"I am their student\"?",opts:["Wǒ shì tāmen de xuéshēng","Tāmen shì wǒ de xuéshēng","Nǐ shì tāmen de xuéshēng","Wǒmen shì tāmen de xuéshēng"],ans:0},
{id:90,cat:"sentences",q:"Which sentence means \"You are my teacher\"?",opts:["Nǐ shì wǒ de lǎoshī","Wǒ shì nǐ de lǎoshī","Tā shì wǒ de lǎoshī","Tāmen shì wǒ de lǎoshī"],ans:0},
{id:91,cat:"sentences",q:"Which sentence means \"They are our students\"?",opts:["Tāmen shì wǒmen de xuéshēng","Wǒmen shì tāmen de xuéshēng","Nǐmen shì tāmen de xuéshēng","Tā shì wǒmen de xuéshēng"],ans:0},
{id:92,cat:"sentences",q:"Which sentence means \"We are your friends\"?",opts:["Wǒmen shì nǐ de péngyou","Nǐ shì wǒmen de péngyou","Tāmen shì nǐ de péngyou","Wǒ shì nǐ de péngyou"],ans:0},
{id:93,cat:"sentences",q:"Which sentence means \"He is their teacher\"?",opts:["Tā shì tāmen de lǎoshī","Tāmen shì tā de lǎoshī","Nǐ shì tāmen de lǎoshī","Wǒ shì tāmen de lǎoshī"],ans:0},
{id:94,cat:"sentences",q:"Which sentence means \"You are their friend\"?",opts:["Nǐ shì tāmen de péngyou","Wǒ shì tāmen de péngyou","Tā shì tāmen de péngyou","Wǒmen shì tāmen de péngyou"],ans:0},
{id:95,cat:"sentences",q:"Which sentence means \"They are my teachers\"?",opts:["Tāmen shì wǒ de lǎoshī","Wǒ shì tāmen de lǎoshī","Nǐ shì tāmen de lǎoshī","Wǒmen shì tāmen de lǎoshī"],ans:0},
{id:96,cat:"sentences",q:"Which sentence means \"I am your friend\"?",opts:["Wǒ shì nǐ de péngyou","Nǐ shì wǒ de péngyou","Tā shì nǐ de péngyou","Wǒmen shì nǐ de péngyou"],ans:0},
{id:97,cat:"sentences",q:"Which sentence means \"He is our student\"?",opts:["Tā shì wǒmen de xuéshēng","Wǒmen shì tā de xuéshēng","Nǐ shì wǒmen de xuéshēng","Tāmen shì wǒmen de xuéshēng"],ans:0},
{id:98,cat:"sentences",q:"Which sentence means \"We are their friends\"?",opts:["Wǒmen shì tāmen de péngyou","Tāmen shì wǒmen de péngyou","Nǐ shì tāmen de péngyou","Tā shì wǒmen de péngyou"],ans:0},
// ===== VOCABULARY (99-118) =====
{id:99,cat:"vocabulary",q:"What is the Chinese word for \"Up\"?",opts:["Xia","Zhong","Shang","Mian"],ans:2},
{id:100,cat:"vocabulary",q:"\"Mid\" in Chinese is:",opts:["Zhong","Shang","Xia","Yi"],ans:0},
{id:101,cat:"vocabulary",q:"What does \"Xia\" mean?",opts:["Up","Middle","Down","Side"],ans:2},
{id:102,cat:"vocabulary",q:"The Chinese word for \"Side\" is:",opts:["Mian","Xia","Zhong","Wu"],ans:0},
{id:103,cat:"vocabulary",q:"\"Today\" in Chinese is:",opts:["Ming tian","Jin tian","Zuo tian","Shi tian"],ans:1},
{id:104,cat:"vocabulary",q:"\"Tomorrow\" in Chinese is:",opts:["Ming tian","Jin tian","Zuo tian","Qi tian"],ans:0},
{id:105,cat:"vocabulary",q:"\"Yesterday\" in Chinese is:",opts:["Jin tian","Ming tian","Zuo tian","Wu tian"],ans:2},
{id:106,cat:"vocabulary",q:"\"Doctor\" in Chinese is:",opts:["Yi sheng","Xian sheng","Xue sheng","Lao shi"],ans:0},
{id:107,cat:"vocabulary",q:"\"Mr.\" in Chinese is:",opts:["Yi sheng","Xian sheng","Zhong sheng","Wu sheng"],ans:1},
{id:108,cat:"vocabulary",q:"\"Student\" in Chinese is:",opts:["Xue sheng","Yi sheng","Lao sheng","Shi sheng"],ans:0},
{id:109,cat:"vocabulary",q:"\"Initial\" in Chinese is:",opts:["Yin mu","Sheng mu","Zhong mu","Shi mu"],ans:1},
{id:110,cat:"vocabulary",q:"\"Final\" in Chinese is:",opts:["Yin mu","Sheng mu","Xue mu","Wu mu"],ans:0},
{id:111,cat:"vocabulary",q:"Jin Tian means:",opts:["Yesterday","Tomorrow","Today","Monday"],ans:2},
{id:112,cat:"vocabulary",q:"Ming Tian means:",opts:["Today","Tomorrow","Yesterday","Sunday"],ans:1},
{id:113,cat:"vocabulary",q:"Zuo Tian means:",opts:["Tomorrow","Yesterday","Today","Monday"],ans:1},
{id:114,cat:"vocabulary",q:"Yi Sheng refers to:",opts:["Doctor","Student","Teacher","Mr."],ans:0},
{id:115,cat:"vocabulary",q:"Xian Sheng refers to:",opts:["Teacher","Doctor","Mr.","Student"],ans:2},
{id:116,cat:"vocabulary",q:"Xue Sheng means:",opts:["Doctor","Student","Teacher","Boss"],ans:1},
{id:117,cat:"vocabulary",q:"Sheng Mu refers to:",opts:["Initial","Final","Middle","Side"],ans:0},
{id:118,cat:"vocabulary",q:"Yin Mu refers to:",opts:["Beginning sound","Ending sound","Final","Side"],ans:2},
// ===== DAYS (119-138) =====
{id:119,cat:"days",q:"Week in Chinese is:",opts:["Xing qi","Yue","Ri","Tian"],ans:0},
{id:120,cat:"days",q:"Monday in Chinese:",opts:["Xing qi yi","Xing qi er","Xing qi san","Xing qi si"],ans:0},
{id:121,cat:"days",q:"Tuesday is:",opts:["Xing qi er","Xing qi san","Xing qi wu","Xing qi liu"],ans:0},
{id:122,cat:"days",q:"Wednesday is:",opts:["Xing qi san","Xing qi si","Xing qi yi","Xing qi wu"],ans:0},
{id:123,cat:"days",q:"Thursday is:",opts:["Xing qi si","Xing qi liu","Xing qi yi","Xing qi san"],ans:0},
{id:124,cat:"days",q:"Friday is:",opts:["Xing qi wu","Xing qi san","Xing qi liu","Xing qi er"],ans:0},
{id:125,cat:"days",q:"Saturday is:",opts:["Xing qi liu","Xing qi qi","Xing qi wu","Xing qi san"],ans:0},
{id:126,cat:"days",q:"Sunday is:",opts:["Xing qi tian","Xing qi wu","Xing qi er","Xing qi yi"],ans:0},
{id:127,cat:"days",q:"Xing qi yi means:",opts:["Monday","Tuesday","Wednesday","Thursday"],ans:0},
{id:128,cat:"days",q:"Xing qi er means:",opts:["Monday","Tuesday","Friday","Sunday"],ans:1},
{id:129,cat:"days",q:"Xing qi san means:",opts:["Monday","Wednesday","Thursday","Sunday"],ans:1},
{id:130,cat:"days",q:"Xing qi si means:",opts:["Tuesday","Wednesday","Thursday","Saturday"],ans:2},
{id:131,cat:"days",q:"Xing qi wu means:",opts:["Friday","Monday","Tuesday","Sunday"],ans:0},
{id:132,cat:"days",q:"Xing qi liu means:",opts:["Saturday","Friday","Sunday","Monday"],ans:0},
{id:133,cat:"days",q:"Xing qi tian means:",opts:["Saturday","Sunday","Monday","Tuesday"],ans:1},
{id:134,cat:"days",q:"Which day is the 3rd day?",opts:["Xing qi san","Xing qi er","Xing qi yi","Xing qi si"],ans:0},
{id:135,cat:"days",q:"Which is the 5th day?",opts:["Xing qi wu","Xing qi si","Xing qi liu","Xing qi san"],ans:0},
{id:136,cat:"days",q:"Which day is after Friday?",opts:["Sunday","Saturday","Monday","Thursday"],ans:1},
{id:137,cat:"days",q:"Which day is before Tuesday?",opts:["Sunday","Monday","Wednesday","Friday"],ans:1},
{id:138,cat:"days",q:"Which day is the last day of week?",opts:["Monday","Sunday","Friday","Wednesday"],ans:1},
// ===== MONTHS (139-158) =====
{id:139,cat:"months",q:"Month in Chinese is:",opts:["Tian","Yue","Ri","Xing"],ans:1},
{id:140,cat:"months",q:"January is:",opts:["Yi Yue","Er Yue","San Yue","Si Yue"],ans:0},
{id:141,cat:"months",q:"February is:",opts:["San Yue","Er Yue","Si Yue","Wu Yue"],ans:1},
{id:142,cat:"months",q:"March is:",opts:["San Yue","Er Yue","Yi Yue","Wu Yue"],ans:0},
{id:143,cat:"months",q:"April is:",opts:["Si Yue","San Yue","Wu Yue","Liu Yue"],ans:0},
{id:144,cat:"months",q:"May is:",opts:["Wu Yue","Liu Yue","Qi Yue","Ba Yue"],ans:0},
{id:145,cat:"months",q:"June is:",opts:["Liu Yue","Qi Yue","Wu Yue","Si Yue"],ans:0},
{id:146,cat:"months",q:"July is:",opts:["Qi Yue","Ba Yue","Jiu Yue","Shi Yue"],ans:0},
{id:147,cat:"months",q:"August is:",opts:["Ba Yue","Qi Yue","Jiu Yue","Shi Yue"],ans:0},
{id:148,cat:"months",q:"September is:",opts:["Shi Yue","Jiu Yue","Shi Yi Yue","Shi Er Yue"],ans:1},
{id:149,cat:"months",q:"October is:",opts:["Shi Yue","Jiu Yue","Shi Yi Yue","Shi Er Yue"],ans:0},
{id:150,cat:"months",q:"November is:",opts:["Shi Yi Yue","Shi Yue","Jiu Yue","Ba Yue"],ans:0},
{id:151,cat:"months",q:"December is:",opts:["Shi Er Yue","Shi Yi Yue","Shi Yue","Ba Yue"],ans:0},
{id:152,cat:"months",q:"Which month is Yi Yue?",opts:["January","February","March","April"],ans:0},
{id:153,cat:"months",q:"Which month is Wu Yue?",opts:["May","June","July","August"],ans:0},
{id:154,cat:"months",q:"Which month is Qi Yue?",opts:["June","July","August","September"],ans:1},
{id:155,cat:"months",q:"Which month is Ba Yue?",opts:["July","August","September","October"],ans:1},
{id:156,cat:"months",q:"Jiu Yue means:",opts:["August","September","October","November"],ans:1},
{id:157,cat:"months",q:"Shi Yue means:",opts:["October","September","November","December"],ans:0},
{id:158,cat:"months",q:"Shi Er Yue means:",opts:["November","December","October","August"],ans:1},
// ===== NUMBERS (159-178) =====
{id:159,cat:"numbers",q:"Zero in Chinese is:",opts:["Yi","Ling","Shi","Wu"],ans:1},
{id:160,cat:"numbers",q:"One in Chinese is:",opts:["Yi","Er","San","Si"],ans:0},
{id:161,cat:"numbers",q:"Two is:",opts:["Er","San","Si","Wu"],ans:0},
{id:162,cat:"numbers",q:"Three is:",opts:["Si","San","Wu","Liu"],ans:1},
{id:163,cat:"numbers",q:"Four is:",opts:["Si","Wu","Qi","Ba"],ans:0},
{id:164,cat:"numbers",q:"Five is:",opts:["Wu","Liu","Qi","Ba"],ans:0},
{id:165,cat:"numbers",q:"Six is:",opts:["Wu","Liu","Qi","Shi"],ans:1},
{id:166,cat:"numbers",q:"Seven is:",opts:["Ba","Qi","Liu","Jiu"],ans:1},
{id:167,cat:"numbers",q:"Eight is:",opts:["Ba","Qi","Shi","Wu"],ans:0},
{id:168,cat:"numbers",q:"Nine is:",opts:["Shi","Ba","Jiu","Qi"],ans:2},
{id:169,cat:"numbers",q:"Ten is:",opts:["Shi","Jiu","Ba","Qi"],ans:0},
{id:170,cat:"numbers",q:"Teacher in Chinese is:",opts:["Lao shi","Yi sheng","Xue sheng","Zhong sheng"],ans:0},
{id:171,cat:"numbers",q:"\"I\" in Chinese is:",opts:["Wo","Ni","Ta","Shi"],ans:0},
{id:172,cat:"numbers",q:"Yi means:",opts:["Two","One","Three","Ten"],ans:1},
{id:173,cat:"numbers",q:"Er means:",opts:["Two","Three","Four","Five"],ans:0},
{id:174,cat:"numbers",q:"San means:",opts:["Four","Three","Five","Six"],ans:1},
{id:175,cat:"numbers",q:"Si means:",opts:["Three","Four","Five","Six"],ans:1},
{id:176,cat:"numbers",q:"Wu means:",opts:["Four","Five","Six","Seven"],ans:1},
{id:177,cat:"numbers",q:"Liu means:",opts:["Five","Six","Seven","Eight"],ans:1},
{id:178,cat:"numbers",q:"Qi means:",opts:["Six","Seven","Eight","Nine"],ans:1},
// ===== GREETINGS (179-198) =====
{id:179,cat:"greetings",q:"What does \"Nǐ hǎo ma?\" mean?",opts:["Good morning","How are you?","What is your name?","Goodbye"],ans:1},
{id:180,cat:"greetings",q:"What is the correct reply to \"Nǐ hǎo ma?\"?",opts:["Wǒ jiào…","Zài jiàn","Wǒ hěn hǎo","Xièxiè"],ans:2},
{id:181,cat:"greetings",q:"What does \"Wǒ hěn hǎo\" mean?",opts:["I am fine","Thank you","My name is","Goodbye"],ans:0},
{id:182,cat:"greetings",q:"What does \"Xièxiè nǐ ne?\" mean?",opts:["Where are you from?","Thanks, and you?","Nice to meet you","What is your name?"],ans:1},
{id:183,cat:"greetings",q:"What does \"Wǒ yě hěn hǎo\" mean?",opts:["I am also fine","I am Chinese","I am from Pakistan","Goodbye"],ans:0},
{id:184,cat:"greetings",q:"What does \"Nǐ jiào shénme míngzi?\" mean?",opts:["Where are you going?","What is your name?","How are you?","Who are you?"],ans:1},
{id:185,cat:"greetings",q:"How do you say \"My name is ___\" in Chinese?",opts:["Wǒ shì","Wǒ jiào","Wǒ yě","Nǐ jiào"],ans:1},
{id:186,cat:"greetings",q:"What does \"Nǐ shì nǎ guó rén?\" mean?",opts:["What is your job?","Which country are you from?","Where do you live?","What is your name?"],ans:1},
{id:187,cat:"greetings",q:"What does \"Wǒ shì Bājīsītǎn rén\" mean?",opts:["I am Chinese","I am Pakistani","I am American","I am a student"],ans:1},
{id:188,cat:"greetings",q:"What does \"Rènshi nǐ hěn gāoxìng\" mean?",opts:["Nice to meet you","Good morning","Thank you","See you later"],ans:0},
{id:189,cat:"greetings",q:"What is the correct reply to \"Rènshi nǐ hěn gāoxìng\"?",opts:["Zài jiàn","Wǒ yě shì","Wǒ jiào","Xièxiè"],ans:1},
{id:190,cat:"greetings",q:"What does \"Wǒ yě shì\" mean?",opts:["I also am / Me too","Thank you","My name is","I am fine"],ans:0},
{id:191,cat:"greetings",q:"What does \"Zài jiàn\" mean?",opts:["Hello","Goodbye","Thank you","Please"],ans:1},
{id:192,cat:"greetings",q:"Which phrase means \"Thank you\"?",opts:["Xièxiè","Zài jiàn","Wǒ jiào","Nǐ hǎo"],ans:0},
{id:193,cat:"greetings",q:"Which phrase is used to ask someone's name?",opts:["Wǒ jiào","Nǐ jiào shénme míngzi?","Wǒ shì","Xièxiè"],ans:1},
{id:194,cat:"greetings",q:"Which phrase means \"Hello / How are you?\"",opts:["Nǐ hǎo ma","Zài jiàn","Xièxiè","Wǒ jiào"],ans:0},
{id:195,cat:"greetings",q:"What does \"Wǒ shì … rén\" indicate?",opts:["Your job","Your nationality","Your age","Your hobby"],ans:1},
{id:196,cat:"greetings",q:"Which sentence means \"Which country are you from?\"",opts:["Nǐ jiào shénme míngzi","Nǐ shì nǎ guó rén","Wǒ jiào","Xièxiè"],ans:1},
{id:197,cat:"greetings",q:"What is the meaning of \"Nǐ hǎo\"?",opts:["Hello","Goodbye","Thank you","Sorry"],ans:0},
{id:198,cat:"greetings",q:"Which phrase is used when leaving someone?",opts:["Xièxiè","Wǒ jiào","Zài jiàn","Wǒ hěn hǎo"],ans:2}
];
